### ISSUE TITLE
How can I configure jira to work with the plugin 2.0 version

### ISSUE THREAD

**Issue by qalinn** [jenkinsci/atlassian-jira-software-cloud-plugin#76]
### Describe your use-case which is not covered by existing documentation.

Hi, 

I have the latest version of the atlassian-jira-software-cloud-plugin (2.0). I noticed the new version is asking about webHookUrl parameter, that means we should install the jenkins jira  app on our jira. 
The documentation for how should be installed/configured on Jira the Jenkins app is missing.
Could you create this?

Thank you!

**Comment by thombergs** [comment]
We're just about to release the Jenkins app for Jira next week. Sorry about that, we couldn't time the release of version 2.0.0 of the plugin and the Jenkins app and the docs all on the same day, so things are going to be a bit mixed up for few days.

If you want to make it work now, you have to install version1 1.4.5 of the plugin, create OAuth credentials in Jira (gear icon -> apps -> Oauth Credentials, make sure to tick "Builds" and "Deployments"), then paste them into the Jenkins config.

If you have a couple more days, you can be one of the first users of our new app, and take advantage of version 2.0.0 of the plugin, which makes the setup of your Jenkinsfiles simpler.

I'll let you know here when the app is released.

**Comment by qalinn** [comment]
@thombergs  Thank you for the quick replay. Yes, I did in the same way how you suggested above. Please let me know when it is ready.

**Comment by mmswiderski** [comment]
@thombergs I am also waiting for information about the new version release :+1:

**Comment by newforma-bclemans** [comment]
+1 subscribed. webHookUrl lack of documentation has introduced breaking changes for our JCasC environment. Rolling back to 1.4.5 until documentation is provided.

**Comment by thombergs** [comment]
Hey all.

Sorry for the delay. The new Jenkins app for Jira is not live in the [Jira Marketplace](https://marketplace.atlassian.com/apps/1227791/jenkins-for-jira-official?tab=overview&hosting=cloud). This app is compatible with version 2.0.0 of the Jenkins plugin and with [these docs](https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin/blob/master/README.md). Some links to docs might still point to old docs, but we are in the process of updating those.

If you have used an older version of the plugin before, note that the new version of the plugin supports sending builds and deployment without having to use the `jiraSendBuildInfo` and `jiraSendDeploymentInfo` commands in your `Jenkinsfile`, which hopefully makes it easier to set up.

If you install the app from the Jira Marketplace, it will guide you through the connection process and show you a webhook URL and secret to configure in Jenkins.

Let us know how it goes. Any feedback is welcome!

**Comment by mvaleiko** [comment]
Hi, I have tried installing the app and I am not getting any build information in Jira.  Is there any way to debug? Testing the connection was successful.

**Comment by thombergs** [comment]
Hey @mvaleiko,

sorry for the late reply. Can you describe all the steps you did? Maybe I can see what's wrong from that description. Otherwise, feel free to open a support case at https://support.atlassian.com/ mentioning the "Jenkins for Jira" app and we'll have a look into the logs.

**Comment by thombergs** [comment]
With version 2.0.5, we introduced a "debug" flag. You can configure this in "Manage Jenkins > Configure System > Jira Software Cloud Integration > Activate debug logging". If this is activated, the Jenkins pipeline logs will contain a bunch of information that shows which issue keys have been extracted from the branch name and commit messages and what data is sent over the wire to Jira.
